import { Validators } from "@angular/forms";
import { FieldsInterface, FormFieldsInterface, FormName } from "../interfaces/form-interface";
import { Injectable } from "@angular/core";
@Injectable({
  providedIn: 'root'
})
export class Fields {
  private Fields:FormFieldsInterface = {
    login: [
      {
        name: 'identifier',
        label: 'Email',
        type: 'email',
        placeholder: 'Email',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Password',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
    ],
    register: [
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        placeholder: "Username",
        validators: [
          Validators.required,
          Validators.minLength(3),
          Validators.maxLength(16),
          Validators.pattern(/^\S*(?:\S+\S)*$/),
        ],
        value: '',
        maxLength: 16,
        messageRequired: 'El campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 3',
        messageMaxLength: 'El Maximo de caracteres son 16',
        disable: false,
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        validators: [
          Validators.required,
          Validators.minLength(5),
          Validators.maxLength(255),
        ],
        value: '',
        maxLength: 255,
        messageRequired: 'EL campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 5',
        messageMaxLength: 'El Maximo de caracteres son 255',
        disable: false,
      },
      {
        name: 'last_name',
        label: 'Last Name',
        type: 'text',
        validators: [
          Validators.required,
          Validators.minLength(5),
          Validators.maxLength(255),
        ],
        value: '',
        maxLength: 255,
        messageRequired: 'Campo requerido',
        messageMinLength: 'El Minimo de caracteres son 5',
        messageMaxLength: 'El Maximo de caracteres son 255',
        disable: false,
      },
      {
        name: 'profile',
        label: 'Profile',
        type: 'file',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        validators: [Validators.required, Validators.email],
        value: '',
        messageRequired: ' El campo es requerido',
        messageEmail: 'El campo debe ser un email',
        disable: false,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        validators: [
          Validators.required,
          Validators.minLength(8),
          Validators.maxLength(16),
          Validators.pattern(
            /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])(?!.*(.)\1)[A-Za-z\d$@$!%*?&]{8,15}(?!\s)/g
          ),
        ],
        value: '',
        maxLength: 16,
        messageRequired: 'El Campo es requerido',
        messagePattern: 'La contraseña debe contener al menos una letra mayúscula, una letra minúscula, un número y un carácter especial ($@$!%*?&) y sin dígitos duplicados ni espacios',
        disable: false,
      },
      {
        name: 'date',
        label: 'Date',
        type: 'date',
        validators: [],
        value: new Date(),
        messageRequired: 'El campo es requerido',
        disable: true,
      },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        validators: [Validators.required],
        value: '1',
        messageRequired: 'El campo es requerido',
        options: [
          // {
          //   value: '3',
          //   label: 'Administrador',
          // },
          {
            value: '1',
            label: 'Usuario',
          },
        ],
        disable: true,
      },
      {
        name: 'address',
        label: 'Address',
        type: 'richtext',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
      {
        name: 'phone',
        label: 'Phone',
        type: 'tel',
        validators: [
          Validators.required,
          Validators.minLength(10),
          Validators.maxLength(10),
        ],
        value: '',
        maxLength: 10,
        messageRequired: 'El campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 10',
        messageMaxLength: 'El Maximo de caracteres son 10',
        disable: false,
      },
    ],
    users: [
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        placeholder: "Username",
        validators: [
          Validators.required,
          Validators.minLength(3),
          Validators.maxLength(16),
          Validators.pattern(/^\S*(?:\S+\S)*$/),
        ],
        value: '',
        maxLength: 16,
        messageRequired: 'El campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 3',
        messageMaxLength: 'El Maximo de caracteres son 16',
        disable: false,
      },
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        validators: [
          Validators.required,
          Validators.minLength(5),
          Validators.maxLength(255),
        ],
        value: '',
        maxLength: 255,
        messageRequired: 'EL campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 5',
        messageMaxLength: 'El Maximo de caracteres son 255',
        disable: false,
      },
      {
        name: 'last_name',
        label: 'Last Name',
        type: 'text',
        validators: [
          Validators.required,
          Validators.minLength(5),
          Validators.maxLength(255),
        ],
        value: '',
        maxLength: 255,
        messageRequired: 'Campo requerido',
        messageMinLength: 'El Minimo de caracteres son 5',
        messageMaxLength: 'El Maximo de caracteres son 255',
        disable: false,
      },
      {
        name: 'profile',
        label: 'Profile',
        type: 'file',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        validators: [Validators.required, Validators.email],
        value: '',
        messageRequired: ' El campo es requerido',
        messageEmail: 'El campo debe ser un email',
        disable: false,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        validators: [
          Validators.required,
          Validators.minLength(8),
          Validators.maxLength(16),
          Validators.pattern(
            /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])(?!.*(.)\1)[A-Za-z\d$@$!%*?&]{8,15}(?!\s)/g
          ),
        ],
        value: '',
        maxLength: 16,
        messageRequired: 'El Campo es requerido',
        messagePattern: 'La contraseña debe contener al menos una letra mayúscula, una letra minúscula, un número y un carácter especial ($@$!%*?&) y sin dígitos duplicados ni espacios',
        disable: false,
      },
      {
        name: 'date',
        label: 'Date',
        type: 'date',
        validators: [],
        value: new Date(),
        messageRequired: 'El campo es requerido',
        disable: true,
      },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        validators: [Validators.required],
        value: '1',
        messageRequired: 'El campo es requerido',
        options: [
          {
            value: '3',
            label: 'Administrador',
          },
          {
            value: '1',
            label: 'Usuario',
          },
        ],
        disable: true,
      },
      {
        name: 'address',
        label: 'Address',
        type: 'richtext',
        validators: [Validators.required],
        value: '',
        messageRequired: 'El campo es requerido',
        disable: false,
      },
      {
        name: 'phone',
        label: 'Phone',
        type: 'tel',
        validators: [
          Validators.required,
          Validators.minLength(10),
          Validators.maxLength(10),
        ],
        value: '',
        maxLength: 10,
        messageRequired: 'El campo es requerido',
        messageMinLength: 'El Minimo de caracteres son 10',
        messageMaxLength: 'El Maximo de caracteres son 10',
        disable: false,
      },
    ],
    currencys: [],
    brands: [],
    cars: [],
    rentals: [],
    types: [],
    clients: [],
    documents: []
  }
  getFields(formName:FormName): FieldsInterface[] {
    return this.Fields[formName];
  }
}
